#!/bin/bash

set -e

# Get a renewable, forwardable ticket
# TODO there should be an option to keep the existing ticket, in case previous
# failures were due to network errors rather than ticket expiry
kinit -r 999h -l 999h -f
# Get AFS tokens, if available
which aklog && aklog
while true
do
	# Renew ticket (also renewable, forwardable), or bail out (set -e)
	# TODO would be better to be able to ignore transient network errors.
	kinit -R -r 999h -l 999h -f
	# Refresh AFS tokens, if possible
	which aklog && aklog
	# Display ticket cache and AFS token cache
	klist
	which tokens && tokens
	# Wait a reasonable time before renewing again
	sleepy 3h
# stderr in red
done 2> >(sed $'s|.*|\e[31m&\e[m|'>&2)
